function CopyAutoGeneratedPeripheralWrappersToTemp(ArduinoServerDir,Arch,Libraries,Package)
%

%   Copyright 2023-2024 The MathWorks, Inc.
builderDir=fullfile(fileparts(codertarget.arduinobase.internal.getSpPkgRootDir),'arduinobase','iobuilder','iobuilder_peripheral_wrappers');

copyfile(fullfile(builderDir,'iobuilder.c'),ArduinoServerDir,'f');
copyfile(fullfile(builderDir,'iobuilder.h'),ArduinoServerDir,'f');
copyfile(fullfile(builderDir,'iobuilder_private.h'),ArduinoServerDir,'f');
copyfile(fullfile(builderDir,'iobuilder_types.h'),ArduinoServerDir,'f');
copyfile(fullfile(builderDir,'rt_defines.h'),ArduinoServerDir,'f');

for libCount = arduinoio.internal.ArduinoConstants.AutogeneratedLibraries
    if any(ismember(libCount,Libraries))
        srcDir = fullfile(fileparts(codertarget.arduinobase.internal.getSpPkgRootDir),'arduinobase','src');
        incDir = fullfile(fileparts(codertarget.arduinobase.internal.getSpPkgRootDir),'arduinobase','include');
        copyfile(fullfile(incDir,'io_wrappers.h'),ArduinoServerDir,'f');
        switch char(libCount)
            case 'InputCapture'
                switch(Arch)
                    case 'sam'
                        copyfile(fullfile(srcDir,'MW_SAM_InputCaptureDriver.c'),ArduinoServerDir,'f');
                    case 'samd'
                        copyfile(fullfile(srcDir,'MW_SAMD_InputCaptureDriver.c'),ArduinoServerDir,'f');
                    case 'avr'
                        if isequal(Package,'teensy')
                            copyfile(fullfile(srcDir,'MW_TEENSY_InputCaptureDriver.cpp'),ArduinoServerDir,'f');
                        else
                            copyfile(fullfile(srcDir,'MW_AVR_InputCaptureDriver.c'),ArduinoServerDir,'f');
                        end
                    case 'mbed'
                        copyfile(fullfile(srcDir,'MW_MBED_InputCaptureDriver.cpp'),ArduinoServerDir,'f');
                end
                copyfile(fullfile(incDir,'MW_InputCaptureDriver.h'),ArduinoServerDir,'f');
            case 'AnalogOutput'
                copyfile(fullfile(srcDir,'MW_analogWriteDAC.cpp'),ArduinoServerDir,'f');
                copyfile(fullfile(incDir,'MW_analogWriteDAC.h'),ArduinoServerDir,'f');
            case {'WiFiTCP','WiFiUDP','WiFiMQTT','WiFiHTTP','WiFiThingspeak'}
                copyfile(fullfile(srcDir,'MW_WiFiInit.cpp'),ArduinoServerDir,'f');
                copyfile(fullfile(incDir,'MW_WiFiInit.h'),ArduinoServerDir,'f');
                if strcmpi(char(libCount),'WiFiTCP')
                    copyfile(fullfile(srcDir,'MW_WiFiTCP.cpp'),ArduinoServerDir,'f');
                    copyfile(fullfile(incDir,'MW_WiFiTCP.h'),ArduinoServerDir,'f');
                end
                if strcmpi(char(libCount),'WiFiUDP')
                    copyfile(fullfile(srcDir,'MW_WiFiUDP.cpp'),ArduinoServerDir,'f');
                    copyfile(fullfile(incDir,'MW_WiFiUDP.h'),ArduinoServerDir,'f');
                end
                if strcmpi(char(libCount),'WiFiMQTT')
                    copyfile(fullfile(incDir,'MW_MQTT_Client.h'),ArduinoServerDir,'f');
                    copyfile(fullfile(srcDir,'MW_MQTT_Client.cpp'),ArduinoServerDir,'f');
                end
                if strcmpi(char(libCount),'WiFiHTTP')
                    copyfile(fullfile(incDir,'MW_ArduinoHttpClient.h'),ArduinoServerDir,'f');
                    copyfile(fullfile(srcDir,'MW_ArduinoHttpClient.cpp'),ArduinoServerDir,'f');
                end
                if strcmpi(char(libCount),'WiFiThingspeak')
                    copyfile(fullfile(srcDir,'MW_thingspeak.cpp'),ArduinoServerDir,'f');
                    copyfile(fullfile(incDir,'MW_thingspeak.h'),ArduinoServerDir,'f');
                    copyfile(fullfile(incDir,'ThingSpeak.h'),ArduinoServerDir,'f');
                    copyfile(fullfile(srcDir,'ThingSpeak.cpp'),ArduinoServerDir,'f');
                    copyfile(fullfile(srcDir,'MW_WiFiInit.cpp'),ArduinoServerDir,'f');
                    copyfile(fullfile(incDir,'MW_WiFiInit.h'),ArduinoServerDir,'f');
                    copyfile(fullfile(srcDir,'MW_WiFiTCP.cpp'),ArduinoServerDir,'f');
                    copyfile(fullfile(incDir,'MW_WiFiTCP.h'),ArduinoServerDir,'f');
                end
            case 'EEPROM'
                copyfile(fullfile(srcDir,'MW_ArduinoOnBoardEEPROM.cpp'),ArduinoServerDir,'f');
                copyfile(fullfile(incDir,'MW_ArduinoOnBoardEEPROM.h'),ArduinoServerDir,'f');
        end
    end
end
end
