function result = precisions()
%

%   Copyright 2017-2022 The MathWorks, Inc.

    result = [ "int8", ...
               "uint8", ...
               "int16", ...
               "uint16", ...
               "int32", ...
               "uint32", ...
               "int64", ...
               "uint64" ];
end
