classdef arduinoPackageInfo < matlab.addons.internal.SupportPackageInfoBase

%   This class ensures that Arduino I/O support package shows up in the
%   list of suggested support package when using deploytool.

%   Copyright 2018-2023 The MathWorks, Inc.

    methods
        function obj = arduinoPackageInfo()
            obj.baseProduct = 'MATLAB';
            obj.displayName = 'MATLAB Support Package for Arduino Hardware';
            obj.name        = 'MATLAB Support Package for Arduino Hardware';

            obj.thirdPartyName{1} = 'Arduino';
            cliVersion = arduinoio.internal.ArduinoConstants.CLIVersion;
            % For Windows platform
            if ispc
                obj.thirdPartyURL{1} = ['https://github.com/arduino/arduino-cli/releases/download/v' cliVersion '/arduino-cli_' cliVersion '_Windows_64bit.zip'];
                % For MAC platform
            elseif ismac
                if strcmpi(computer,'MACA64')
                    obj.thirdPartyURL{1} = ['https://github.com/arduino/arduino-cli/releases/download/v' cliVersion '/arduino-cli_' cliVersion '_macOS_ARM64.tar.gz'];
                else
                    obj.thirdPartyURL{1} = ['https://github.com/arduino/arduino-cli/releases/download/v' cliVersion '/arduino-cli_' cliVersion '_macOS_64bit.tar.gz'];
                end
                % For Linux platform
            elseif isunix && ~ismac
                obj.thirdPartyURL{1} = ['https://github.com/arduino/arduino-cli/releases/download/v' cliVersion '/arduino-cli_' cliVersion '_Linux_64bit.tar.gz'];
            end

            sproot = matlabshared.supportpkg.getSupportPackageRoot();
            arduinoSourceRoot = arduinoio.SPPKGRoot();
            sharedArduinoRoot = arduinoio.SharedArduinoRoot();
            deviceDriverRoot = matlabshared.devicedrivers.internal.getDeviceDriverRootDir();

            % Package all the files in these folders.
            % Revert back to fullfile(sensorRoot) for specifying sensor
            % files for compilation once g2596070 is submitted
            obj.mandatoryIncludeList = {...
                ... Resource Catalog ...
                fullfile(sproot, 'resources', 'MATLAB', 'en', 'arduinoio') ...
                fullfile(sproot, 'resources', 'MATLAB', 'en', 'hwsdk') ...
                fullfile(sproot, 'resources', 'MATLAB', 'en', 'hwshared') ...
                ... HWSDK ...
                fullfile(arduinoSourceRoot, '..', '..', 'shared', 'hwsdk') ...
                fullfile(deviceDriverRoot) ...
                ... Arduino Support Package ...
                ... Class file ...
                fullfile(arduinoSourceRoot, 'arduino.m') ...
                ... Sensor infrastructure ...
                ... Custom peripherals ...
                fullfile(arduinoSourceRoot, '+arduinoio') ...
                fullfile(sharedArduinoRoot, '+arduinoio') ...
                fullfile(sharedArduinoRoot, 'target') ...
                ... Add Ons ...
                fullfile(arduinoSourceRoot, '+arduinoioaddons') ...
                ... Arduino Libraries ...
                fullfile(arduinoSourceRoot, 'listArduinoLibraries.m') ...
                ... DDUX impl not to break Compiler workflow ...
                fullfile(sproot, 'toolbox', 'matlab', 'hardware', 'shared', 'ddux', '+matlabshared') ...
                   };

            % Suggest SPKG name only when a function from arduino.m is called
            obj.conditionalIncludeMap = containers.Map;
            obj.conditionalIncludeMap(fullfile(arduinoSourceRoot, 'arduino.m')) = {};
        end
    end
end
