classdef AnalogInput < matlabshared.ioclient.debugPeripheralClass
    
    % This class stores the debug messages generated by Analog input on
    % Arduino
    
    %   Copyright 2018 The MathWorks, Inc.
    
    properties(Access = protected)
        DebugMessageMap = containers.Map('KeyType', 'double', 'ValueType', 'any')
    end
    properties(Constant)
        AnalogInSingleRead = 06
    end
    
    methods
        function obj = AnalogInput()
            obj.DebugMessageMap(obj.AnalogInSingleRead) = {"ArduinoTraceOn::analogRead(%d); --> %d\n", 'uint8', 'uint16'};            
        end
    end
end