classdef DigitalIO < matlabshared.ioclient.debugPeripheralClass
    
    % This class stores the debug messages generated by Digital IO on
    % Arduino
    
    %   Copyright 2018-2019 The MathWorks, Inc.
    
    properties(Access = protected)
        DebugMessageMap = containers.Map('KeyType', 'double', 'ValueType', 'any');
        OutputStatusMap = containers.Map('KeyType', 'double', 'ValueType', 'char');
        PinModeMap      = containers.Map('KeyType', 'double', 'ValueType', 'char');
    end
    properties(Constant)
        PinMode                         = 0
        DigitalWrite                    = 1
        DigitalRead                     = 2
        DEBUGUNCONFIGUREDIGITALPIN      = 4
    end
    
    methods
        function obj = DigitalIO()
            % Although the format specifier is given in the debug message
            % string, the data type of each argument has to be provided
            % because on the target the arguments are not always provided
            % memory according to the format specifier.
            obj.DebugMessageMap(obj.PinMode) = {"ArduinoTraceOn::pinMode(%d, %s);\n", 'uint8', 'string'};            
            obj.DebugMessageMap(obj.DigitalWrite) = {"ArduinoTraceOn::digitalWrite(%d, %s);\n", 'uint8', 'string'};
            obj.DebugMessageMap(obj.DigitalRead) = {"ArduinoTraceOn::digitalRead(%d); -->%s\n", 'uint8', 'string'};
            obj.DebugMessageMap(obj.DEBUGUNCONFIGUREDIGITALPIN) = {"UnconfigureDigitalPin::pinMode(%d, %s);\n", 'uint8', 'string'};  
            % Map the strings denoting output state of a pin
            obj.OutputStatusMap(1) = 'HIGH';
            obj.OutputStatusMap(0) = 'LOW';
            %Map the strings denoting the mode of a pin
            obj.PinModeMap(0) = 'INPUT';
            obj.PinModeMap(1) = 'OUTPUT';
            obj.PinModeMap(2) = 'INPUT_PULLUP';
        end
    end
    
    methods(Access = protected)
        function mapObj = getStringMapObjImpl(obj, messageId, ~)
            switch messageId
                case {obj.PinMode, obj.DEBUGUNCONFIGUREDIGITALPIN}
                    mapObj = obj.PinModeMap;
                case {obj.DigitalRead, obj.DigitalWrite}
                    mapObj = obj.OutputStatusMap;
            end
        end
    end
end