classdef I2C < matlabshared.ioclient.debugPeripheralClass
    
    % This class stores the debug messages generated by I2C on Arduino
    
    %   Copyright 2018-2019 The MathWorks, Inc.
    
    properties(Access = protected)
        DebugMessageMap = containers.Map('KeyType', 'double', 'ValueType', 'any');
    end
    properties(Constant)
        DEBUGI2CBEGINAVR                = 20;
        DEBUGI2CBEGINARM                = 21;
        DEBUGI2CSETCLOCKAVR             = 22;
        DEBUGI2CSETCLOCKARM             = 23;
        DEBUGI2CREQUESTFROMAVR          = 24;
        DEBUGI2CREQUESTFROMARM          = 25;
        DEBUGI2CREADFROMAVR             = 26;
        DEBUGI2CREADFROMARM             = 27;
        DEBUGI2CBEGINTRANSMISSIONAVR    = 28;
        DEBUGI2CWRITEAVR                = 29;
        DEBUGI2CENDTRANSMISSIONAVR      = 19;
        DEBUGI2CBEGINTRANSMISSIONARM    = 18;
        DEBUGI2CWRITEARM                = 17;
        DEBUGI2CENDTRANSMISSIONARM      = 16;
        DEBUGI2CWRITEAVR1DATA           = 15;
        DEBUGI2CWRITEAVR2DATA           = 14;
        DEBUGI2CWRITEAVR3DATA           = 13; 
        DEBUGI2CWRITEARM1DATA           = 12;
        DEBUGI2CWRITEARM2DATA           = 11;
        DEBUGI2CWRITEARM3DATA           = 10;
    end
    
    methods
        function obj = I2C()
            obj.DebugMessageMap(obj.DEBUGI2CBEGINAVR) = {"Arduino::Wire.begin();\n"};
            obj.DebugMessageMap(obj.DEBUGI2CBEGINARM) = {"Arduino::Wire1.begin();\n"};
            obj.DebugMessageMap(obj.DEBUGI2CSETCLOCKAVR) = {"Arduino::Wire.setClock(%ld);\n", 'uint32'};
            obj.DebugMessageMap(obj.DEBUGI2CSETCLOCKARM) = {"Arduino::Wire1.setClock(%ld);\n", 'uint32'};
            obj.DebugMessageMap(obj.DEBUGI2CREQUESTFROMAVR) = {"Arduino::Wire.requestFrom(%d, %d, %d); --> %d\n", 'uint8', 'uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CREQUESTFROMARM) = {"Arduino::Wire1.requestFrom(%d, %d, %d); --> %d\n", 'uint8', 'uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CREADFROMAVR) = {"Arduino::Wire.read(); --> %d\n", 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CREADFROMARM) = {"Arduino::Wire1.read(); --> %d\n", 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CBEGINTRANSMISSIONAVR) = {"Arduino::Wire.beginTransmission(%d);\n", 'uint8'};   % address in uint8
            obj.DebugMessageMap(obj.DEBUGI2CWRITEAVR) = {"Arduino::Wire.write(%d); --> %d\n", 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CENDTRANSMISSIONAVR) = {"Arduino::Wire.endTransmission(%d); --> %d\n", 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CBEGINTRANSMISSIONARM) = {"Arduino::Wire1.beginTransmission(%d);\n", 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CWRITEARM) = {"Arduino::Wire1.write(%d); --> %d\n", 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CENDTRANSMISSIONARM) = {"Arduino::Wire1.endTransmission(%d); --> %d\n", 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CWRITEAVR1DATA) = {"Arduino::Wire.write([%d], %d); --> %d\n", 'uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CWRITEAVR2DATA) = {"Arduino::Wire.write([%d, %d], %d); --> %d\n", 'uint8', 'uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CWRITEAVR3DATA) = {"Arduino::Wire.write([%d, %d, %d,...], %d); --> %d\n", 'uint8', 'uint8', 'uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CWRITEARM1DATA) = {"Arduino::Wire1.write([%d], %d); --> %d\n", 'uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CWRITEARM2DATA) = {"Arduino::Wire1.write([%d, %d], %d); --> %d\n", 'uint8', 'uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGI2CWRITEARM3DATA) = {"Arduino::Wire1.write([%d, %d, %d, ...], %d); --> %d\n", 'uint8', 'uint8', 'uint8', 'uint8', 'uint8'};
        end
    end
end