classdef PlayTone < matlabshared.ioclient.debugPeripheralClass
    % This class stores the debug messages generated by Playtone on Arduino
    
    %   Copyright 2018 The MathWorks, Inc.
    
    properties(Access = protected)
        DebugMessageMap = containers.Map('KeyType', 'double', 'ValueType', 'any');
    end
    
    properties(Constant)
        DEBUGPLAYTONE   = 65;
    end
    
    methods
        function obj = PlayTone()
            obj.DebugMessageMap(obj.DEBUGPLAYTONE) = {"Arduino::playTone(%u, %u, %u);\n", 'uint8', 'uint16', 'uint16'};
        end
    end
end