classdef PWM < matlabshared.ioclient.debugPeripheralClass
    
    % This class stores the debug messages generated by PWM on Arduino
    
    %   Copyright 2018-2021 The MathWorks, Inc.
    
    properties(Access = protected)
        DebugMessageMap = containers.Map('KeyType', 'double', 'ValueType', 'any');
        PinModeMap = containers.Map('KeyType', 'double', 'ValueType', 'char');
    end
    
    properties(Constant)
        SetDutyCycle = 40;
        SetDutyCycleESP32 = 42;
        DEBUGPWMOPEN = 41;
    end
    
    methods
        function obj = PWM()
            obj.DebugMessageMap(obj.SetDutyCycle) = {"Arduino::analogWrite(%d, %d);\n", 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.SetDutyCycleESP32) = {"Arduino::ledcWrite(%d, %d,%d);\n", 'uint8', 'uint8','uint8'};
            % Verify this message
            obj.DebugMessageMap(obj.DEBUGPWMOPEN) = {"PWMConfigure::Arduino::pinMode(%d, %s);\n", 'uint8', 'string'};
            % String map
            obj.PinModeMap(1) = 'OUTPUT';
            obj.PinModeMap(0) = 'INPUT';
        end
    end
    
    methods(Access = protected)
        function mapObj = getStringMapObjImpl(obj, messageId, ~)
            if(messageId == obj.DEBUGPWMOPEN)
                mapObj = obj.PinModeMap;
            end
        end
    end
end