classdef RotaryEncoder < matlabshared.ioclient.debugPeripheralClass
    
    % This class stores the debug messages generated by Rotary encoder on Arduino
    
    %   Copyright 2018-2019 The MathWorks, Inc.
    
    properties(Access = protected)
        DebugMessageMap = containers.Map('KeyType', 'double', 'ValueType', 'any');
        OutputStatusMap = containers.Map('KeyType', 'double', 'ValueType', 'char');
    end
    
    properties(Constant)
        DEBUGATTACHENCODER           = 81;
        DEBUGDETACHENCODER           = 82;
        DEBUGREADSPEEDENCODER        = 83;
        DEBUGREADCOUNTENCODER        = 85;
        DEBUGWRITWCOUNTENCODER       = 86;
    end
    
    methods
        function obj = RotaryEncoder()
            obj.DebugMessageMap(obj.DEBUGATTACHENCODER) = {"RotaryEncoder::attachInterrupt(%d,isrPin%c%d, CHANGE);\n", 'uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGDETACHENCODER) = {"RotaryEncoder::detachInterrupt(%d);\nRotaryEncoder::detachInterrupt(%d);\n", 'uint8', 'uint8'};
            % The target should pass ID also and it is -> "RotaryEncoder::delay(%d);ID %d, overflowDiff --> %d, countDiff --> %d;\n"
            obj.DebugMessageMap(obj.DEBUGREADSPEEDENCODER) = {"RotaryEncoder::delay(%d); overflowDiff --> %d, countDiff --> %d;\n", 'uint8', 'uint8', 'uint16'};
            obj.DebugMessageMap(obj.DEBUGREADCOUNTENCODER) = {"RotaryEncoder::Overflow --> %d;\nmyEncoder[%d].count --> %ld;\n", 'uint8', 'uint8', 'uint32'};
            obj.DebugMessageMap(obj.DEBUGWRITWCOUNTENCODER) = {"RotaryEncoder::myEncoder[%d].count = %ld;\n", 'uint8', 'uint32'};
        end
    end    
end