classdef SCI < matlabshared.ioclient.debugPeripheralClass
    
    % This class stores the debug messages generated by I2C on Arduino
    
    %   Copyright 2019 The MathWorks, Inc.
    
    properties(Access = protected)
        DebugMessageMap = containers.Map('KeyType', 'double', 'ValueType', 'any');
        ParityMap = containers.Map('KeyType', 'double', 'ValueType', 'char');
    end
    properties(Constant)
        DEBUGSCIBEGIN                = 90;
        DEBUGSCISETTIMEOUT           = 91;
        DEBUGSCIWRITE1BYTE           = 92;
        DEBUGSCIWRITE2BYTE           = 93;
        DEBUGSCIWRITE3BYTE           = 94;
        DEBUGSCIREAD1BYTE            = 95;
        DEBUGSCIREAD2BYTE            = 96;
        DEBUGSCIREAD3BYTE            = 97;
        DEBUGSCIAVAILABLE            = 98;
        DEBUGSCIEND                  = 99;
    end
    
    methods
        function obj = SCI()
            obj.DebugMessageMap(obj.DEBUGSCIBEGIN) = {"Arduino::Serial%d.begin(%ld,SERIAL_%d%s%d);\n",'uint8','uint32','uint8','string','uint8'};
            obj.DebugMessageMap(obj.DEBUGSCISETTIMEOUT) = {"Arduino::Serial%d.setTimeout(%ld);\n",'uint8','uint32'};
            obj.DebugMessageMap(obj.DEBUGSCIWRITE1BYTE) = {"Arduino::Serial%d.write([%d], %d); \n", 'uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGSCIWRITE2BYTE) = {"Arduino::Serial%d.write([%d,%d], %d); \n", 'uint8','uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGSCIWRITE3BYTE) = {"Arduino::Serial%d.write([%d,%d,%d....], %d); \n", 'uint8','uint8','uint8', 'uint8','uint8'};
            obj.DebugMessageMap(obj.DEBUGSCIREAD1BYTE) = {"Arduino::Serial%d.readBytes([%d], %d); \n", 'uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGSCIREAD2BYTE) = {"Arduino::Serial%d.readBytes([%d,%d], %d); \n", 'uint8','uint8', 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGSCIREAD3BYTE) = {"Arduino::Serial%d.readBytes([%d,%d,%d....], %d); \n", 'uint8','uint8','uint8', 'uint8','uint8'};
            obj.DebugMessageMap(obj.DEBUGSCIAVAILABLE) = {"Arduino::Serial%d.available; --> %d\n", 'uint8','uint8'};
            obj.DebugMessageMap(obj.DEBUGSCIEND) = {"Arduino::Serial%d.end();\n", 'uint8'};

         % Map the strings denoting Parity configured
            obj.ParityMap(0) = 'N';
            obj.ParityMap(1) = 'E';
            obj.ParityMap(2) = 'O';
        end
    end
    
        methods(Access = protected)
         function mapObj = getStringMapObjImpl(obj, messageId, ~)
            if(messageId == obj.DEBUGSCIBEGIN)
                mapObj = obj.ParityMap;
            end
        end
   end
end
