classdef Servo < matlabshared.ioclient.debugPeripheralClass
    
    % This class stores the debug messages generated by Servo on Arduino
    
    %   Copyright 2018-2022 The MathWorks, Inc.
        
    properties(Access = protected)
        DebugMessageMap = containers.Map('KeyType', 'double', 'ValueType', 'any');
    end
    properties(Constant)
        DetachServo             = 50;
        ReadPosition            = 51;
        WritePosition           = 52;
        DEBUGSERVOATTACH        = 53;
        DEBUGSERVOATTACH_ARM    = 54;
        DEBUGSERVOATTACH_ESP32  = 55;
    end
    
    methods
        function obj = Servo()
            obj.DebugMessageMap(obj.DetachServo) = {"Arduino::servoArray[%d]->detach();\n", 'uint8'};
            obj.DebugMessageMap(obj.ReadPosition) = {"Arduino::servoArray[%d]->read() -> %d;\n", 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.WritePosition) = {"Arduino::servoArray[%d]->write(%d);\n", 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGSERVOATTACH) = {"Arduino::servoArray[%d] = new Servo;\nArduino::servoArray[%d]->attach(%d, %d, %d)... 0x%04X;\n", 'uint8', 'uint8', 'uint8', 'uint16', 'uint16', 'uint16'};
            obj.DebugMessageMap(obj.DEBUGSERVOATTACH_ARM) = {"Arduino::servoArray[%d] = new Servo;\nArduino::servoArray[%d]->attach(%d, %d, %d)... 0x%08X;\n", 'uint8', 'uint8', 'uint8', 'uint16', 'uint16', 'uint32'};
            obj.DebugMessageMap(obj.DEBUGSERVOATTACH_ESP32) = {"Arduino::servoArray[%d] = new Servo;\nArduino::servoArray[%d]->attach(%d, %d, %d, %d)... 0x%08X;\n", 'uint8', 'uint8','uint8', 'uint8', 'uint16', 'uint16', 'uint32'};
        end
    end
end