classdef ShiftRegister < matlabshared.ioclient.debugPeripheralClass
    
    % This class stores the debug messages generated by Shift Register on Arduino
    
    %   Copyright 2018-2019 The MathWorks, Inc.
        
    properties(Access = protected)
        DebugMessageMap = containers.Map('KeyType', 'double', 'ValueType', 'any');
        StringMapWrite = containers.Map('KeyType', 'double', 'ValueType', 'char');
        BitOrderMap     = containers.Map('KeyType', 'double', 'ValueType', 'char');
    end
    properties(Constant)
        DEBUGWRITEDIGITALPIN_LOADPIN_CEPIN  = 70;
        DEBUGSHIFTREGISTERWRITE             = 71;
        DEBUGSHIFTOUT                       = 72;
        DEBUGSHIFTIN                        = 73;
    end
    
    methods
        function obj = ShiftRegister()
            obj.DebugMessageMap(obj.DEBUGSHIFTREGISTERWRITE) = { "ShiftRegister::digitalWrite(%d, %s);\n", 'uint8', 'string'};
            obj.DebugMessageMap(obj.DEBUGSHIFTOUT) = {"Arduino::shiftOut(%d, %d, %s, %d);\n", 'uint8', 'uint8', 'string', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGSHIFTIN) = {"Arduino::shiftIn(%d, %d, %s) --> %d;\n", 'uint8', 'uint8', 'string', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGWRITEDIGITALPIN_LOADPIN_CEPIN) = {"ShiftRegister::digitalWrite(%d, %s);\nShiftRegister::digitalWrite(%d, %s);\nShiftRegister::digitalWrite(%d, %s);\n",...
                                                                          'uint8', 'string', 'uint8', 'string', 'uint8', 'string'};
            
            % Update string Maps
            obj.StringMapWrite(0) = "LOW";
            obj.StringMapWrite(1) = "HIGH";
            
            obj.BitOrderMap(0) = 'LSBFIRST';
            obj.BitOrderMap(1) = 'MSBFIRST';
        end
    end
    methods(Access = protected)
        function mapObj = getStringMapObjImpl(obj, messageId, ~)
            switch(messageId)
                case {obj.DEBUGWRITEDIGITALPIN_LOADPIN_CEPIN, obj.DEBUGSHIFTREGISTERWRITE}
                    mapObj = obj.StringMapWrite;
                case {obj.DEBUGSHIFTIN, obj.DEBUGSHIFTOUT}
                    mapObj = obj.BitOrderMap;
            end
        end
    end
end