classdef SPI < matlabshared.ioclient.debugPeripheralClass
    
    % This class stores the debug messages generated by SPI on Arduino
    
    %   Copyright 2018 The MathWorks, Inc.
        
    properties(Access = protected)
        DebugMessageMap = containers.Map('KeyType', 'double', 'ValueType', 'any');
        BitOrderMap     = containers.Map('KeyType', 'double', 'ValueType', 'char');
        SPIModeMap      = containers.Map('KeyType', 'double', 'ValueType', 'char');
        SPITransferMap  = containers.Map('KeyType', 'double', 'ValueType', 'char');
    end
    properties(Constant)
        SPIOpen_ARCH_SAM            = 30;
        SPIOpen                     = 31;        
        SPIWriteRead                = 32;
        SPIClose_ARCH_SAM           = 33;
        SPIClose                    = 34;
        DEBUGSPIBEGINTRANSACTION    = 35;
        DEBUGSPITRANSFERARM         = 36;
        DEBUGSPITRANSFERAVR         = 37;
    end
    
    methods
        function obj = SPI()
            obj.DebugMessageMap(obj.SPIOpen_ARCH_SAM) = {"Arduino::SPI.begin(%d);\n", 'uint8'};
            obj.DebugMessageMap(obj.SPIOpen) = {"Arduino::SPI.begin();\n"};
            obj.DebugMessageMap(obj.SPIWriteRead) = {"Arduino::SPI.endTransaction();\n"};
            obj.DebugMessageMap(obj.SPIClose_ARCH_SAM) = {"Arduino::SPI.end(%d);\n", 'uint8'};
            obj.DebugMessageMap(obj.SPIClose) = {"Arduino::SPI.end();\n"};
            obj.DebugMessageMap(obj.DEBUGSPIBEGINTRANSACTION) = {"Arduino::SPI.beginTransaction(SPISettings(%lu, %s, %s));\n", 'uint32', 'string', 'string'};
            obj.DebugMessageMap(obj.DEBUGSPITRANSFERAVR) = {"Arduino::SPI.transfer(%d); --> %d\n", 'uint8', 'uint8'};   %Check the message string and aRGUMENTS
            obj.DebugMessageMap(obj.DEBUGSPITRANSFERARM) = {"Arduino::SPI.transfer(%d, %d, %s); --> %d\n", 'uint8', 'uint8', 'string', 'uint8'};            %Check the message string and aRGUMENTS
            
            % Map for string arguments
            obj.BitOrderMap(0) = 'LSBFIRST';
            obj.BitOrderMap(1) = 'MSBFIRST';
            obj.SPIModeMap(0)  = 'SPI_MODE0';
            obj.SPIModeMap(1)  = 'SPI_MODE1';
            obj.SPIModeMap(2)  = 'SPI_MODE2';
            obj.SPIModeMap(3)  = 'SPI_MODE3';
            obj.SPITransferMap(0) = 'SPI_CONTINUE';
            obj.SPITransferMap(1) = 'SPI_LAST';
        end
    end
    
    methods(Access = protected)        
        function mapObj = getStringMapObjImpl(obj, messageId, stringArgumentIndex)
            switch(messageId)
                case obj.DEBUGSPIBEGINTRANSACTION
                    if(stringArgumentIndex == 1)
                        mapObj = obj.BitOrderMap;
                    elseif(stringArgumentIndex == 2)
                        mapObj = obj.SPIModeMap;
                    end
                case obj.DEBUGSPITRANSFERARM
                    mapObj = obj.SPITransferMap;
            end
        end
    end
end