classdef Ultrasonic < matlabshared.ioclient.debugPeripheralClass
    
    % This class stores the debug messages generated by Ultrasonic peripheral on Arduino
    
    %   Copyright 2018-2019 The MathWorks, Inc.
    
    properties(Access = protected)
        DebugMessageMap = containers.Map('KeyType', 'double', 'ValueType', 'any');
        OutputStatusMap = containers.Map('KeyType', 'double', 'ValueType', 'char');
    end
    properties(Constant)
        DEBUGDELAYMICROSECONDS = 60;
        DEBUGDELETEULTRASONIC  = 61;
        DEBUGCREATEULTRASONIC  = 62;
        DEBUGPULSEIN           = 63;
    end
    
    methods
        function obj = Ultrasonic()
            obj.DebugMessageMap(obj.DEBUGDELAYMICROSECONDS) = {"Arduino::delayMicroseconds(%d);\n", 'uint8'};
            obj.DebugMessageMap(obj.DEBUGDELETEULTRASONIC) = {"Ultrasonic::detach();\n"};
            obj.DebugMessageMap(obj.DEBUGCREATEULTRASONIC) = {"Ultrasonic::attach(triggerPin: %d, echoPin: %d);\n", 'uint8', 'uint8'};
            obj.DebugMessageMap(obj.DEBUGPULSEIN) = {"Arduino::pulseIn(%d, %s, %d) --> %d; \n", 'uint8', 'string', 'uint32', 'uint32'};
            
            % Updating string map
            obj.OutputStatusMap(0) = 'LOW';
            obj.OutputStatusMap(1) = 'HIGH';
        end
    end
    
    methods(Access = protected)
        function mapObj = getStringMapObjImpl(obj, messageId, ~)
            if(messageId == obj.DEBUGPULSEIN)
                mapObj = obj.OutputStatusMap;
            end
        end
    end
end